id: A1BB1B4DB
title: Daily Practice of Dorje Gotrab
type: translation
pechas:
- IA714A1F9
- IDFA54F98
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:49:26.059186
  last_modified_at: 2023-01-04 11:49:26.059198
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IA714A1F9/A7E7: '2285'
  IDFA54F98/5005: '2285'
